version: '3.8'

services:
    dev:
        build: .
          context: backend
          target: development
        ipc: host
        ports:
          - 82:82
        volumes:
          - .:/code
          - "~/.gitconfig:/etc/gitconfig" # carry over username
          - "/mnt/c/Users/ejc01/AppData/Roaming/Code/User:/root/.local/share/code-server" # carry over local VS code settings
          - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519 # carry over SSH key
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
    
        command: bash -c "nvidia-smi && jupyter lab --ip=0.0.0.0 --port=81 --no-browser --allow-root --LabApp.token=''"
